FROM python:3.11-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY spark_jobs/requirements-beam.txt .
RUN pip install -r requirements-beam.txt

COPY spark_jobs/beam_lambda_ingestion.py .

ENTRYPOINT ["python", "beam_lambda_ingestion.py"]
