version: '3.8'
x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # Default GCP project and json path inside container
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-credentials.json
    GCP_PROJECT_ID: hybrid-elt-lakehouse-pipeline
    # Ép Airflow nhận thẳng Connection qua biến môi trường để không bao giờ bị lỗi kết nối
    AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: 'google-cloud-platform://?extra__google_cloud_platform__key_path=%2Fopt%2Fairflow%2Fgcp-credentials.json&extra__google_cloud_platform__project=hybrid-elt-lakehouse-pipeline'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    # Mount the GCP credentials dynamically based on user setup
    - ../data_generator/hybrid-elt-lakehouse-pipeline-2110462e33d2.json:/opt/airflow/gcp-credentials.json:ro
    # Mount dbt model files to run inside Airflow container
    - ../dbt_transform:/opt/airflow/dbt_transform
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    environment:
      <<: *airflow-common-env
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  data-generator:
    build:
      context: ../data_generator
      dockerfile: Dockerfile
    # Map .env variables to the container
    env_file:
      - ../.env
    volumes:
      # Map the credentials file dynamically
      - ../data_generator/hybrid-elt-lakehouse-pipeline-2110462e33d2.json:/app/credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
